name: 更新个人开发动态

on:
  schedule:
    - cron: "0 1 * * 1"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 生成开发动态卡片
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ultralan
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
